apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: monitoring
spec:
  mode: daemonset
  hostNetwork: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:3030"
      otlp/trace:
        protocols:
          http:
            endpoint: "0.0.0.0:4318"
    exporters:
      otlp/jaeger:
        endpoint: "tempo.monitoring.svc:14250"
        tls:
          insecure: true
      logging:
      loki:
        endpoint: http://loki.monitoring.svc:3100/loki/api/v1/push
      prometheus:
        endpoint: "0.0.0.0:8889"
    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [loki]
        traces:
          receivers: [otlp/trace]
          exporters: [logging, otlp/jaeger]
        metrics:
          receivers: [otlp]
          exporters: [logging, prometheus]